stages:
  - test
  - build
  - deploy

unit-test:
  image: node
  script:
    - npm ci
    - npm test

build:
  stage: build
  image: node
  script:
    - npm ci
    - npm run build
  artifacts:
    paths:
      - dist
    expire_in: 30 days