name: RNG Documentation

on:
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15.x ]

    steps:
      - uses: actions/checkout@v1
      - name: Prepare
        run: git config --global user.email "rieser.daniel@gmail.com"
      - name: Generate
        uses: tool3/docsify-action@v1.1
        with:
          github_token: ${{ secrets.GP_TOKEN }}


